image: Ubuntu
build_script:
  - sh: |-
      dotnet test
      dotnet build
test: off
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
artifacts:
  - path: 'src\Fractions\bin\Release\*.nupkg'
    type: NuGetPackage
  - path: 'src\Fractions.Json\bin\Release\*.nupkg'
    type: NuGetPackage